### ISSUE TITLE
Can't change gamma value.

### ISSUE THREAD

**Issue by norpol** [pisto/sdos-test#8]
Hi, 
first a huge thank you for putting efforts in porting sauerbraten to SDL2.
Now the issue, I can't change the gamma-value by /gamma or over the GUI. I'm using an Intel HD4000 'GPU' (i5 processor).

**Comment by pisto** [comment]
In case you still care, check this out http://www.sauerworld.org/c2svn/ . It's going to replace the master branch soon.

**Comment by norpol** [comment]
Thank you for letting me know. I'll test it when the source is available. :)

**Comment by pisto** [comment]
This is the source https://github.com/pisto/sdos-test/tree/sdl2-upstream

**Comment by norpol** [comment]
I see, works. Not sure yet why it doesn't save my configuration.
