### ISSUE TITLE
SDL2 fails to build on Arch Linux

### ISSUE THREAD

**Issue by tpoechtrager** [pisto/sdos-test#9]
libtool: link: ( cd ".libs" && rm -f "libSDL2_image.la" && ln -s "../libSDL2_image.la" "libSDL2_image.la" )
    /bin/sh ./libtool  --tag=CC   --mode=link cc  -I/development/3rd/sdos-test/deps/linux64/include/libpng16 -I/development/3rd/sdos-test/deps/linux64/include -pthread -m64  -O3 -fomit-frame-pointer -fvisibility=hidden -D_REENTRANT -I/development/3rd/sdos-test/deps/linux64/include/SDL2  -I/development/3rd/sdos-test/deps/linux64/include -pthread -m64  -O3 -fomit-frame-pointer -fvisibility=hidden -L/development/3rd/sdos-test/deps/linux64/lib -o showimage showimage.o libSDL2_image.la -L/development/3rd/sdos-test/deps/linux64/lib -Wl,-rpath,/development/3rd/sdos-test/deps/linux64/lib -lSDL2
    libtool: link: cc -I/development/3rd/sdos-test/deps/linux64/include/libpng16 -I/development/3rd/sdos-test/deps/linux64/include -pthread -m64 -O3 -fomit-frame-pointer -fvisibility=hidden -D_REENTRANT -I/development/3rd/sdos-test/deps/linux64/include/SDL2 -I/development/3rd/sdos-test/deps/linux64/include -pthread -m64 -O3 -fomit-frame-pointer -fvisibility=hidden -o showimage showimage.o -Wl,-rpath -Wl,/development/3rd/sdos-test/deps/linux64/lib  -L/development/3rd/sdos-test/deps/linux64/lib ./.libs/libSDL2_image.a /development/3rd/sdos-test/deps/linux64/lib/libpng16.a -lz /development/3rd/sdos-test/deps/linux64/lib/libjpeg.a /development/3rd/sdos-test/deps/linux64/lib/libSDL2.a -lm -ldl -lpthread -lrt -pthread
    /development/3rd/sdos-test/deps/linux64/lib/libSDL2.a(SDL_waylandvideo.o): In function `display_handle_global':
    SDL_waylandvideo.c:(.text+0x5b3): undefined reference to `wl_proxy_marshal_constructor_versioned'
    SDL_waylandvideo.c:(.text+0x5f4): undefined reference to `wl_proxy_marshal_constructor_versioned'
    SDL_waylandvideo.c:(.text+0x63d): undefined reference to `wl_proxy_marshal_constructor_versioned'
    SDL_waylandvideo.c:(.text+0x6a4): undefined reference to `wl_proxy_marshal_constructor_versioned'
    SDL_waylandvideo.c:(.text+0x6ec): undefined reference to `wl_proxy_marshal_constructor_versioned'
    /development/3rd/sdos-test/deps/linux64/lib/libSDL2.a(SDL_waylandvideo.o):SDL_waylandvideo.c:(.text+0x71b): more undefined references to `wl_proxy_marshal_constructor_versioned' follow
    collect2: error: ld returned 1 exit status
    Makefile:516: recipe for target 'showimage' failed
    make: *** [showimage] Error 1

https://hg.libsdl.org/SDL/rev/330f500d5815

**Comment by pisto** [comment]
you are testing t e-upstream branches right?

**Comment by pisto** [comment]
fixed 3726520a1747d0db48d054ba62e4bb322355cca3
